default:
  image: openjdk:17
  before_script:
    - git config --global user.name "gitlab"
    - git config --global user.email noreply@proxora.com

maven-build:
  script: ./mvnw -e -B -V clean package